/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Base1Container: typeof import('./components/base1Container.vue')['default']
    Base1NavBar: typeof import('./components/base1NavBar.vue')['default']
    Base1RefreshList: typeof import('./components/base1RefreshList.vue')['default']
    Base1TabBar: typeof import('./components/base1TabBar.vue')['default']
    BaseContainer: typeof import('./components/baseContainer.vue')['default']
    BaseNavBar: typeof import('./components/baseNavBar.vue')['default']
    BaseRefreshList: typeof import('./components/baseRefreshList.vue')['default']
    BaseTabBar: typeof import('./components/baseTabBar.vue')['default']
    Chart: typeof import('./components/Chart/index.vue')['default']
    RefreshList: typeof import('./components/RefreshList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
