/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/baseButton.vue')['default']
    BaseCellHead: typeof import('./components/baseCellHead.vue')['default']
    BaseContainer: typeof import('./components/baseContainer.vue')['default']
    BaseGiftPrice: typeof import('./components/baseGiftPrice.vue')['default']
    BaseHead: typeof import('./components/baseHead.vue')['default']
    BaseHeadTool: typeof import('./components/baseHeadTool.vue')['default']
    BaseNavBar: typeof import('./components/baseNavBar.vue')['default']
    BasePopup: typeof import('./components/basePopup.vue')['default']
    BaseRefreshList: typeof import('./components/baseRefreshList.vue')['default']
    BaseTabBar: typeof import('./components/baseTabBar.vue')['default']
    BaseTabs: typeof import('./components/baseTabs.vue')['default']
    BaseTag: typeof import('./components/baseTag.vue')['default']
    BaseTextLink: typeof import('./components/baseTextLink.vue')['default']
    BaseTitle: typeof import('./components/baseTitle.vue')['default']
    copy: typeof import('./components/baseHead copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
