/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/baseButton.vue')['default']
    BaseCellHead: typeof import('./components/baseCellHead.vue')['default']
    BaseContainer: typeof import('./components/baseContainer.vue')['default']
    BaseGiftPrice: typeof import('./components/baseGiftPrice.vue')['default']
    BaseHeadTool: typeof import('./components/baseHeadTool.vue')['default']
    BaseKeyboard: typeof import('./components/baseKeyboard.vue')['default']
    BaseMainPage: typeof import('./components/baseMainPage.vue')['default']
    BaseNavBar: typeof import('./components/baseNavBar.vue')['default']
    BasePopup: typeof import('./components/basePopup.vue')['default']
    BaseRefreshList: typeof import('./components/baseRefreshList.vue')['default']
    BaseSearch: typeof import('./components/baseSearch.vue')['default']
    BaseSelect: typeof import('./components/baseSelect.vue')['default']
    BaseSound: typeof import('./components/baseSound.vue')['default']
    BaseTabBar: typeof import('./components/baseTabBar.vue')['default']
    BaseTabs: typeof import('./components/baseTabs.vue')['default']
    BaseTag: typeof import('./components/baseTag.vue')['default']
    BaseTagSelect: typeof import('./components/baseTagSelect.vue')['default']
    BaseTextLink: typeof import('./components/baseTextLink.vue')['default']
    BaseTitle: typeof import('./components/baseTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
