/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/components/rules/thePoint24RulesForm': RouteRecordInfo<'/components/rules/thePoint24RulesForm', '/components/rules/thePoint24RulesForm', Record<never, never>, Record<never, never>>,
    'game': RouteRecordInfo<'game', '/game', Record<never, never>, Record<never, never>>,
    'gamePoint24': RouteRecordInfo<'gamePoint24', '/game/point24', Record<never, never>, Record<never, never>>,
    'gameSnake': RouteRecordInfo<'gameSnake', '/game/snake', Record<never, never>, Record<never, never>>,
    'gift': RouteRecordInfo<'gift', '/gift', Record<never, never>, Record<never, never>>,
    'giftCustom': RouteRecordInfo<'giftCustom', '/gift/custom', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'orderGift': RouteRecordInfo<'orderGift', '/order/gift', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'profile/child': RouteRecordInfo<'profile/child', '/profile/child', Record<never, never>, Record<never, never>>,
    'recordIntegral': RouteRecordInfo<'recordIntegral', '/record/integral', Record<never, never>, Record<never, never>>,
    'story': RouteRecordInfo<'story', '/story', Record<never, never>, Record<never, never>>,
    'storyCustom': RouteRecordInfo<'storyCustom', '/story/custom', Record<never, never>, Record<never, never>>,
    'storyLevel': RouteRecordInfo<'storyLevel', '/story/level/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'storyLevelCustom': RouteRecordInfo<'storyLevelCustom', '/story/level/:id/custom', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'task': RouteRecordInfo<'task', '/task', Record<never, never>, Record<never, never>>,
    'taskCustom': RouteRecordInfo<'taskCustom', '/task/custom', Record<never, never>, Record<never, never>>,
    'words': RouteRecordInfo<'words', '/words', Record<never, never>, Record<never, never>>,
  }
}
